### ISSUE TITLE
Logged out of Steam crash

### ISSUE THREAD

**Issue by WilliamVenner** [timschumi/gmod-steamhttp#1]
Is this module intended to work if you don't have Steam open and logged in?

Appears to crash on both release versions if you're not logged into Steam.

**Comment by timschumi** [comment]
At the moment, no. In general, this project is quite unstable anyways.

The SteamAPI is (in my opinion) poorly documented as a whole, and it being a closed-source part doesn't help either.

I don't know how the internal HTTP module works without logging in (since it internally relies on SteamHTTP as well), but it doesn't seem to work for my module.

I'm already checking for API init failures though and printing a warning, maybe I should turn that into a hard fail in the future.

**Comment by WilliamVenner** [comment]
thank you for making the module :)

I've switched to chttp for now.

**Comment by timschumi** [comment]
steamhttp is now officially deprecated, so it's unlikely that I will ever fix this issue. :^)
